CREATE OR REPLACE FILE FORMAT DW_PROD."PUBLIC"."TSV_ZIPCODES"
    type = 'TSV'
    FIELD_DELIMITER = '\t'
    SKIP_HEADER = 15555
    COMPRESSION = NONE
    ENCODING = 'UTF-8'
    COMMENT = ' demo 1'
;
