resource "snowflake_procedure" "AWS_LANDING_INGEST_DB_WORKDAY_TRUNCATE_TABLES" {
	name ="TRUNCATE_TABLES"
	database = "AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}"
	schema = "WORKDAY"
	language  = "SQL"
	return_type = "VARCHAR(16777216)"
	execute_as = "OWNER"
	statement = <<-EOT 


BEGIN
--- Truncate AWS Landing Area Tables
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.QUALIFICATIONS_CERTIFICATION_ACHIEVEMENT;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.RELATED_PERSON_ADDRESS_DATA;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.WORKER_ADDITIONAL_INFORMATION;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.WORKER_ADDRESS_DATA;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.WORKER_COMPENSATION;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.WORKER_LEAVE_OF_ABSENCE;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.WORKER_ORGANIZATION_DATA;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.WORKER_SUMMARY;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.WORKER_SUPERVISOR;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.WORKER_EMAIL_DATA;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.WORKER_PHONE_DATA;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.AUDIT;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.RELATED_PERSON;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.RELATED_PERSON_EMAIL_DATA;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.RELATED_PERSON_NAME_DATA;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.RELATED_PERSON_PHONE_DATA;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.WORKER_IDENTIFICATION_DATA;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.WORKER_PERSONAL;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.WORKER_POSITION_DATA;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.WORKER_STATUS;
TRUNCATE TABLE AWS_LANDING_INGEST_DB_${var.SF_ENVIRONMENT}.WORKDAY.WORKER_NAME_DATA;


    return 'Success';
END;

 EOT
}

